# Generated by Django 6.0.1 on 2026-01-13 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'Title must be at least 2 characters long!')])),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('material', models.CharField(blank=True, max_length=40, null=True)),
                ('season', models.CharField(choices=[('all', 'All-Season'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='all')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, 'Price must be at least 0')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wardrobe', to='wardrobe.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wardrobe', to='wardrobe.category')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['category', 'brand'], name='wardrobe_ga_categor_ff3121_idx'), models.Index(fields=['season'], name='wardrobe_ga_season_220719_idx')],
            },
        ),
    ]
