# Generated by Django 6.0.1 on 2026-01-18 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
