# Generated by Django 6.0.1 on 2026-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('Tops', [('tshirt', 'T-Shirt'), ('shirt', 'Shirt'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie')]), ('Bottoms', [('jeans', 'Jeans'), ('trousers', 'Trousers'), ('shorts', 'Shorts'), ('skirt', 'Skirt')]), ('Outerwear', [('jacket', 'Jacket'), ('coat', 'Coat')]), ('Footwear', [('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals')]), ('Accessories', [('bag', 'Bag'), ('belt', 'Belt'), ('scarf', 'Scarf'), ('sunglasses', 'Sunglasses')])], max_length=30),
        ),
        migrations.RenameIndex(
            model_name='garment',
            new_name='wardrobe_ga_categor_acb318_idx',
            old_name='wardrobe_ga_categor_ff3121_idx',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
