# Generated by Django 6.0.1 on 2026-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_alter_garment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
