# Generated by Django 6.0.1 on 2026-02-01 16:57

import wardrobe.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_garment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('All', [('', 'All Categories')]), ('Tops', [('tshirt', 'T-Shirt'), ('shirt', 'Shirt'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie')]), ('Bottoms', [('jeans', 'Jeans'), ('trousers', 'Trousers'), ('shorts', 'Shorts'), ('skirt', 'Skirt')]), ('Outerwear', [('jacket', 'Jacket'), ('coat', 'Coat')]), ('Footwear', [('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals')]), ('Accessories', [('bag', 'Bag'), ('belt', 'Belt'), ('scarf', 'Scarf'), ('sunglasses', 'Sunglasses')])], max_length=30),
        ),
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wardrobe/', validators=[wardrobe.validators.ImageSizeValidator('Image size should not exceed 5MB')]),
        ),
        migrations.AlterField(
            model_name='garment',
            name='season',
            field=models.CharField(choices=[('', 'All Seasons'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default=''),
        ),
    ]
