# Generated by Django 6.0.1 on 2026-04-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_default_user(apps, schema_editor):
    """Create a default user with pk=1 if one doesn't exist (needed for seeded garments)."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    if not User.objects.filter(pk=1).exists():
        User.objects.create(
            pk=1,
            email="seed@wearly.app",
            is_active=True,
        )
    # Reset the sequence so auto-increment starts after pk=1
    db_table = User._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT setval(pg_get_serial_sequence('{db_table}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM {db_table}), 1));"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("wardrobe", "0007_seed_comprehensive_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(ensure_default_user, migrations.RunPython.noop),
        migrations.AddField(
            model_name="garment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
