# Generated by Django 6.0.1 on 2026-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wardrobe", "0009_seed_brands_garments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garment",
            name="season",
            field=models.CharField(
                choices=[
                    ("", "All Seasons"),
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("autumn", "Autumn"),
                    ("winter", "Winter"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
