services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: wearlydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A Wearly_Fashion_App worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A Wearly_Fashion_App beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
