# Generated by Django 6.0.1 on 2026-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="is_access_initial",
            field=models.BooleanField(default=True),
        ),
    ]
