# Generated by Django 6.0.1 on 2026-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_seed_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofilemodel",
            name="style_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casual", "Casual"),
                    ("formal", "Formal"),
                    ("streetwear", "Streetwear"),
                    ("minimalist", "Minimalist"),
                    ("eclectic", "Eclectic"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
