# Generated by Django 6.0.1 on 2026-01-14 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'Title must be at least 2 characters long!')])),
                ('season', models.CharField(choices=[('all', 'All-Season'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='all')),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outfits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outfits.occasion')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitGarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('outerwear', 'Outerwear'), ('accessory', 'Accessory')])),
                ('order', models.IntegerField(default=1)),
                ('is_key_piece', models.BooleanField(default=False)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wardrobe.garment', unique=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfits.outfit')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
