# Generated by Django 6.0.1 on 2026-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0004_remove_outfit_wardrobe_outfit_garments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="occasion",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Occasion",
        ),
    ]
