# Generated by Django 6.0.1 on 2026-02-09 22:26

from django.db import migrations, models

import wardrobe.validators


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0005_alter_outfit_occasion_delete_occasion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="outfits/",
                validators=[
                    wardrobe.validators.ImageSizeValidator(
                        "Image size should not exceed 5MB!"
                    )
                ],
            ),
        ),
    ]
