# Generated by Django 6.0.1 on 2026-02-10 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0006_alter_outfit_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outfitgarment",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="outfitgarment",
            name="is_key_piece",
        ),
        migrations.RemoveField(
            model_name="outfitgarment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="outfitgarment",
            name="role",
        ),
    ]
