# Generated by Django 6.0.1 on 2026-04-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0008_alter_outfit_season"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outfits",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
