# Generated by Django 6.0.1 on 2026-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0011_seed_outfits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ('created_at',)},
        ),
    ]
