# Generated by Django 6.0.1 on 2026-04-19 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0013_alter_outfit_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outfit",
            options={
                "ordering": ("created_at",),
                "permissions": [("can_create_styleboard", "Can create style boards")],
            },
        ),
    ]
