# Generated by Django 6.0.1 on 2026-04-19 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outfits", "0014_add_custom_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="styleboard",
            name="is_public",
        ),
    ]
