# Generated by Django 6.0.1 on 2026-01-14 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("outfits", "0002_alter_outfitgarment_garment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Note must be at least 5 characters long!"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="outfits.outfit"
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "indexes": [
                    models.Index(fields=["date"], name="planner_pla_date_9ec209_idx")
                ],
            },
        ),
    ]
