# Generated by Django 6.0.1 on 2026-01-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_alter_outfitgarment_garment_and_more'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planentry',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planentry', to='outfits.outfit'),
        ),
    ]
