# Generated by Django 6.0.1 on 2026-01-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_planentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planentry',
            options={'ordering': ('date',), 'verbose_name': 'Plan Entry', 'verbose_name_plural': 'Plan Entries'},
        ),
    ]
