# Generated by Django 6.0.1 on 2026-04-19 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0006_seed_plan_entries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planentry",
            options={
                "ordering": ("date",),
                "permissions": [
                    ("can_trigger_digest", "Can trigger weekly digest email")
                ],
                "verbose_name": "Plan Entry",
                "verbose_name_plural": "Plan Entries",
            },
        ),
    ]
